name: anilist

on:
  workflow_dispatch:
  schedule:
    # Once a week "At 00:00 on Sunday" (see https://crontab.guru/once-a-week)
    - cron: "0 0 * * 0"

jobs:
  update-pool:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # 3-hours
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run -A packs/anilist/pool.ts
      - name: Upload Pool As Artifact
        uses: actions/upload-artifact@v3
        with:
          name: anilist-pool
          path: packs/anilist/pool.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          author: GitHub <noreply@github.com>
          title: 'Updated "anilist/pool.json"'
          commit-message: '[bot] Updated "anilist/pool.json"'
          branch: update-anilist-pool
          delete-branch: true
          body: |
            This PR is auto-generated

            Updated the pool cache for each possible gacha query

            (See #9)
            (See #45)
          labels: |
            anilist
