name: deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_review:
    types: [submitted]
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno test -A --coverage=cov_profile --no-check
      - run: deno coverage cov_profile --lcov --output=lcov.info
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    if: github.event_name == 'push' # event push only runs on main
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno run -A db/ensureIndexes.ts
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - uses: denoland/deployctl@v1
        with:
          project: ${{ secrets.DENO_ID }}
          entrypoint: src/interactions.ts
