name: deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_review:
    types: [submitted]
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno test -A --coverage=cov_profile tests db update_commands.test.ts
      - run: deno coverage cov_profile --lcov --output=lcov.info
      - uses: codecov/codecov-action@v3

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run -A db/ensureIndexes.ts
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
      - uses: denoland/deployctl@v1
        with:
          project: ${{ secrets.DENO_ID }}
          entrypoint: src/interactions.ts
