name: discord

on:
  push:
    branches:
      - main

jobs:
  update-slash-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Update global slash commands on stable
        env:
          APP_ID: ${{ secrets.APP_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: deno run --allow-read --allow-env --allow-net update_commands.ts
