name: topgg

on:
  workflow_dispatch:
  schedule:
    # Everyday "At 00:00" (see https://crontab.guru/daily)
    - cron: "0 0 * * *"

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Set environment variables
        run: >
          echo "APP_ID=${{ secrets.APP_ID }}" >> "$GITHUB_ENV" |
          echo "FAUNA_SECRET=${{ secrets.FAUNA_SECRET }}" >> "$GITHUB_ENV" |
          echo "TOPGG_TOKEN=${{ secrets.TOPGG_TOKEN }}" >> "$GITHUB_ENV"

      - name: Update top.gg stats
        run: deno run -A update_topgg_stats.ts
